<!--codigo ordenado-->

<div class="container" style="width: 100%;">
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="menuUsuario.php">Menú Usuario</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="menuUsuario.php">Home</a></li>
            <li><a href="tareaUsuario.php">Tareas</a></li>
            <li><a href="proyectoUsuario.php">Proyectos</a></li>
        </ul>
        <div class="right">
            <a href="../Controlador/cerrarSesion.php?" class="btn-xs btn-danger" role="button" style="margin-left: 60%;">Cerrar sesión</a>	
        </div>
    </div>
</nav>
        </div>
        <div class="col-lg-1"></div>
    </div>   
</div>