<!--codigo ordenado-->
<div class="container" style="width: 100%;">
    <div class="row">
        <div class="col-lg-12">
            <nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="menuAdmin.php">Menú Administrador</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="menuAdmin.php">Home</a></li>
            <li><a href="tareaAdmin.php">Tareas</a></li>
            <li><a href="usuario.php">Usuarios</a></li>
            <li><a href="proyectoAdmin.php">Proyectos</a></li>
        </ul>
        <div class="right">
            <a href="../Controlador/cerrarSesion.php?" class="btn-xs btn-danger" role="button" style="margin-left: 55%;">Cerrar sesión</a>	
        </div>
    </div>
</nav>
        </div>
    </div>   
</div>

